
#include <vector>
#include <cstdio>
#include <cstdint>
#include <cassert>
#include "gcd_machine.hpp"

// This is a test harness for the module gcd_machine
// It is generated by Koika and is intended to be used with fuzzing tools.
// The harness provides an interface to set assertion predicates and run simulations.

// set_assert_pred : to set the assertion predicate you want
// pred must be callable of type : const(snapshot_t)& -> bool

// clear_assert_pred : to clear the assertion predicate

// run_fuzz : to run the simulation for n cycles with fuzzing support
// Registers:
//  - input_data : struct pair { a: bits 16; b: bits 16 } (kind: value)
//  - input_valid : bits 1 (kind: value)
//  - output_data : bits 16 (kind: value)

// The input format of the input seed should be consistent with the input format expected by the module
struct extfuns {};
using simulator = module_gcd_machine<extfuns>;
using snapshot_t = simulator::snapshot_t;
using state_t = simulator::state_t;
int main(int argc, char **argv) {

   if (argc != 2) return 1;

   const char *input_path = argv[1]; // input harness file path
   FILE *f = fopen(input_path, "rb"); // read in binary mode

   if (!f) {
       fprintf(stderr, "Error: unable to open %s\n", input_path);
       return 1;
   } 

   std::vector<uint8_t> buf; 
   fseek(f, 0, SEEK_END); // move to end of file
   long file_size = ftell(f); // get file size
   fseek(f, 0, SEEK_SET); // move back to start of file
   if (file_size > 0){
       buf.resize(file_size); // resize buffer to fit file size
       fread(buf.data(), 1, file_size, f); // read file into buffer
   } else {
       fprintf(stderr, "Error: unable to read from %s\n", input_path);
       return 1;
   }
   fclose(f); // close file
// Total input size: 7 bytes
   prims::bits<32> input_data = prims::bits<32>::mk(0);
   prims::bits<8> input_valid = prims::bits<8>::mk(0);
   prims::bits<16> output_data = prims::bits<16>::mk(0);
   const std::size_t expected_bytes =7;
   if (buf.size() < expected_bytes) {
     buf.resize(expected_bytes, 0);
   } else if (buf.size() > expected_bytes) {
     buf.resize(expected_bytes);
   }
   for (std::size_t i = 0; i < 4; ++i) {
     auto b = prims::widen<32>(prims::bits<8>::mk(buf[0 + i]));
     input_data = input_data | (b << (8 * i)); 
   }

   for (std::size_t i = 0; i < 1; ++i) {
     auto b = prims::widen<8>(prims::bits<8>::mk(buf[4 + i]));
     input_valid = input_valid | (b << (8 * i)); 
   }

   for (std::size_t i = 0; i < 2; ++i) {
     auto b = prims::widen<16>(prims::bits<8>::mk(buf[5 + i]));
     output_data = output_data | (b << (8 * i)); 
   }

    simulator::state_t st = simulator::initial_state();
 st.input_data = prims::unpack<decltype(st.input_data)>(input_data); 
 st.input_valid = prims::bits<1>::mk(input_valid);
 st.output_data = prims::bits<16>::mk(output_data);
    simulator sim(st); 
    sim.set_assert_pred([](const snapshot_t& snap) -> bool { // define assertions as lambda function for now
   return true; // set assertion predicate here
   });
   uint64_t ncycles = 1000; 
   sim.run_fuzz(ncycles); // run_fuzz is fuzzing method
  return 0;
}
