(*! Harness backend !*)

open Common 
open Cpp

let harness_cpp_fname = "harness.cpp"
let libraries = ["<vector>"; "<cstdio>";  "<cstdint>";  "<cassert>"]

(* COPIED OVER FOR NOW, THINK OF BETTER SOLUTION ? don't want to change cpp.ml too much*)
let buffer = ref (Buffer.create 0) 
let nl _ = Buffer.add_string !buffer "\n"
let pk k fmt = Printf.kbprintf k !buffer fmt 
let p fmt = pk nl fmt 
let pr fmt = pk ignore fmt 
let p_buffer b = Buffer.add_buffer !buffer b 
let set_buffer b = let b' = !buffer in buffer := b; b' 

let with_output_to_buffer (pbody: unit -> unit) =
    let buf = set_buffer (Buffer.create 4096) in
    pbody ();
    set_buffer buf 
 
    (* COPY STOP*)
let h_preamble (modname: string) () : unit =
    nl ();
    List.iter (fun lib -> p "#include %s" lib) libraries; 
    p "#include \"%s.hpp\"" modname;
    nl ()

let h_used_fun () : unit = 
 p "struct extfuns {}";
 p "using simulator = module_collatz<extfuns>;"; 
 p "using snapshot_t = simulator::snapshot_t;";
 p "using state_t = simulator::state_t;"


let h_description (modname: string) () : unit =
    p "// This is a test harness for the module %s" modname;
    p "// It is generated by Koika and is intended to be used with fuzzing tools.";
    p "// The harness provides an interface to set assertion predicates and run simulations.";
    nl (); 
    (* registers here how ? *)
    p "// set_%s : to set the assertion predicate you want" Cpp.assert_n; 
    p "// pred must be callable of type : const(snapshot_t)& -> bool"; 
    nl(); 
    p "// clear_%s : to clear the assertion predicate" Cpp.assert_n;
    nl ();
    p "// %s : to run the simulation for n cycles with fuzzing support" Cpp.run_fuzz

let iter_registers (cu : (_,_,_,_,_,_) cpp_input_t) f =
  Array.iter (fun r ->
    let sg = cu.cpp_register_sigs r in
    let typ = reg_type sg in 
    f r sg typ) cu.cpp_registers

let h_registers (cu : (_,_,_,_,_,_) cpp_input_t) () : unit =
  p "// Input Registers:";
  iter_registers cu (fun r sg typ ->
     let string_of_typ = typ_to_string typ in
     p "//  - %s : %s" sg.reg_name string_of_typ
  );
  nl (); 
  p "// The input format of the input seed should be consistent with the input format expected by the module"

let h_static_seed_file () : unit = 
  p "   if (argc != 2) return 1;"; 
  nl (); 
  p "   const char *input_path = argv[1]; // input harness file path" ; 
  p "   FILE *f = fopen(input_path, \"rb\"); // read in binary mode" ; 
  nl ();  
  p "   if (!f) {"; 
  p "       fprintf(stderr, \"Error: unable to open %%s\\n\", input_path);" ; 
  p "       return 1;";
  p "   } "; 
  nl (); 
  p "   std::vector<uint8_t> buf; "; 
  p "   fseek(f, 0, SEEK_END); // move to end of file" ; 
  p "   long file_size = ftell(f); // get file size"; 
  p "   fseek(f, 0, SEEK_SET); // move back to start of file"; 
  p "   if (file_size > 0){" ; 
  p "       buf.resize(file_size); // resize buffer to fit file size"; 
  p "       fread(buf.data(), 1, file_size, f); // read file into buffer"; 
  p "   } else {"; 
  p "       fprintf(stderr, \"Error: unable to read from %%s\\n\", input_path);";
  p "       return 1;";
  p "   }";
  p "   fclose(f); // close file"


let register_sizes (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) : (string * int * int * int) list =
  let (_, acc_rev) = Array.fold_left (fun (off, acc) r ->
    let sg = cu.cpp_register_sigs r in
    let bits = typ_sz (reg_type sg) in
    let bytes = (bits + 7) / 8 in
    let entry = (sg.reg_name, bits, bytes, off) in 
    (off + bytes, entry :: acc) 
  ) (0, [] ) cu.cpp_registers in 
  List.rev acc_rev

let input_size_calculation (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) () : unit = 
  let register_sizes_ = register_sizes cu in
  let total_input_size = List.fold_left (fun acc (_,_, sz,_) -> acc + sz) 0 register_sizes_ in (* could I just use last offset of register_sizes + last byte value ?*)
  p "// Total input size: %d bytes" total_input_size; 
  List.iter (fun (nm, bits, _, _) -> 
    p "   uint%d_t %s = 0;" bits nm; (* is this enough ???, think we can ignore any input formatting and pass in binary directly ?  *)
    p "   const std::size_t expected_bytes =%d;" total_input_size; 
  ) register_sizes_;
  p "   if (buf.size() < expected_bytes) {"; (* this or abort when using the wrong size ? *)
  p "     buf.resize(expected_bytes, 0);";
  p "   } else if (buf.size() > expected_bytes) {";
  p "     buf.resize(expected_bytes);";
  p "   }"; 
  List.iter (fun (nm, bits, bytes, off) -> 
    p "   for (std::size_t i = 0; i < %d; ++i) {" bytes;
    p "     %s |= uint%d_t(buf[%d + i]) << (8 * i);" nm bits off;
    p "   }"; 
    nl (); 
  ) register_sizes_

let sim_name = "st"

(* TO DO AUTO ASSIGN WHATEVER WAS READ OUT, need case distinction on all 4 possible types, reg, array, enum, struct
check if method already exists*)
let h_simulator_setup () : unit = 
  p "    simulator::state_t %s = simulator::initial_state();" sim_name;
  p "    simulator sim(st); "; 
  p "    sim.set_assert_pred([](const snapshot_t& snap) -> bool { // define assertions as lambda function for now"; 
  p "    // example assertion predicate that checks if r0 is even"; 
  p "   return snap.state.r0.v != 0; " ; 
  p "   });"; 
  p "   sim.%s(ncycles); // run_fuzz is fuzzing method" Cpp.run_fuzz

let h_main (cpp_in : (_,_,_,_,_,_) Cpp.cpp_input_t) () : unit = 
  let p_ext_fun = with_output_to_buffer h_used_fun in
  let p_static_seed = with_output_to_buffer h_static_seed_file in
  let input_siz_cal = with_output_to_buffer (input_size_calculation cpp_in) in
  let h_sim = with_output_to_buffer h_simulator_setup in
  p_buffer p_ext_fun;
  p "int main(int argc, char **argv) {";
  nl (); 
  p_buffer p_static_seed; 
  p_buffer input_siz_cal; 
  p_buffer h_sim;
  p "  return 0;";
  p "}"


let h_cpp (modname: string) (cpp_in : (_,_,_,_,_,_) Cpp.cpp_input_t) () =
    let preamble_buf = with_output_to_buffer (h_preamble modname) in 
    let description_buf = with_output_to_buffer (h_description modname) in
    let registers_buf = with_output_to_buffer (h_registers cpp_in) in 
    p_buffer preamble_buf;
    p_buffer description_buf; 
    p_buffer registers_buf;
    h_main cpp_in ()

let write_harness_cpp (target_dpath : string) (modname : string) (cpp_in : (_,_,_,_,_,_) Cpp.cpp_input_t): unit =
  let fpath = Filename.concat target_dpath harness_cpp_fname in
  let out_buf = with_output_to_buffer (h_cpp modname cpp_in) in
  with_output_to_file fpath Buffer.output_buffer out_buf

  
let main target_dpath (co_modname : string) (cpp_in : (_,_,_,_,_,_) Cpp.cpp_input_t)  =
  write_harness_cpp target_dpath co_modname cpp_in
  (* let typ_of_value = function
  | Bits bs -> Bits_t (Array.length bs)
  | Enum (sg, _) -> Enum_t sg
  | Struct (sg, _) -> Struct_t sg
  | Array (sg, _) -> Array_t sg*)

