(*! Harness backend !*)

open Common 
open Cpp

let harness_cpp_fname = "harness.cpp"
let n_sim_init = "st"
let n_sim = "sim" 
let n_seed_buf = "buf"
let n_set_init_fn = "set_init" 
let n_set_inputs_fn = "set_inputs"  
let n_set_init_and_input_fn ="set_init_and_inputs"
let n_decode_fn = "decode_path_for"
let n_assert_fn = "assert_fn"
let n_assert_final = "assert_final"
let harness_ns = "harness"
let fn_dump_state = "dump_state"

let n_mode_helper = "beak_mode"

let n_InitBytes = "InitBytes"
let n_InputBytes = "InputBytesPerCycle"

let nSeedPairs = "kSeedPairs"

let n_extfuns_impl = "extfuns_impl"

let n_crashlogP = "CrashLogPath"
let libraries = ["<vector>"; "<cstdio>";  "<cstdint>";  "<cassert>";"<string>"; "<cstring>"; "<cerrno>"]


(* COPIED OVER FOR NOW, THINK OF BETTER SOLUTION ? don't want to change cpp.ml too much*)
let buffer = ref (Buffer.create 0) 
let nl _ = Buffer.add_string !buffer "\n"
let pk k fmt = Printf.kbprintf k !buffer fmt 
let p fmt = pk nl fmt 
let pr fmt = pk ignore fmt 
let p_buffer b = Buffer.add_buffer !buffer b 
let set_buffer b = let b' = !buffer in buffer := b; b' 

let p_comment fmt =
    pr "/* "; pk (fun _ -> pr " */"; nl ()) fmt 

let p_scoped header ?(terminator="") pbody =
    p "%s {" header;
    let r = pbody () in
    p "}%s" terminator;
    r 
let p_fn ~typ ~name ?(args="") ?(annot="") pbody =
    p_scoped (sprintf "%s %s(%s)%s" typ name args annot) pbody 

let with_output_to_buffer (pbody: unit -> unit) =
    let buf = set_buffer (Buffer.create 4096) in
    pbody ();
    set_buffer buf 
 
    (* COPY STOP*)
let h_preamble (modname: string) (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) () : unit =
    nl ();
    List.iter (fun lib -> p "#include %s" lib) libraries; 
    p "#include \"%s.hpp\"" modname;
    p "#include \"harness_support.hpp\"";
    p "#include \"beak_mode.hpp\"";
    p "#include \"assertions.hpp\"";
    nl (); 
    (match cu.cpp_extfuns with
      | None -> p "struct extfuns {};"
      | Some preamble -> p "%s" preamble)

let h_sim_setup (modname : string)() : unit = 
 p "using simulator = module_%s<extfuns_t>;" modname; 
 p "using snapshot_t = simulator::snapshot_t;";
 p "using state_t = simulator::state_t;"; 
 p "static std::string %s = \"\";" n_crashlogP

let h_description (modname: string) () : unit =
    p "// This is a test harness for the module %s" modname;
    p "// It is generated by Koika and is intended to be used with fuzzing tools.";
    p "// The harness provides an interface to set assertion predicates and run simulations.";
    nl (); 
    (* registers here how ? *)
    (* p "// set_%s : to set the assertion predicate you want" Cpp.assert_n;  *)
    p "// pred must be callable of type : const(snapshot_t)& -> bool"; 
    nl(); 
    (* p "// clear_%s : to clear the assertion predicate" Cpp.assert_n; *)
    nl ();
    p "// %s : to run the simulation for n cycles with fuzzing support" Cpp.run_fuzz

type reg_layout = {
  name : string;
  typ  : typ; 
  kind : Extr.register_kind;
  bits : int;
  bytes: int;
  off  : int;
}

type io = Input | Output | Function

type io_layout = {
  name : string;
  type_n : string; 
  io : io; 
  typ  : typ; 
  rettyp : typ; 
  argtyp : typ;
  rettyp_n: string; 
  argtyp_n: string;
  bits : int;
  bytes: int;
  off  : int;
}

let h_print_rule_names (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) () : unit =
  p "// Rules:";
  List.iter (fun rl ->
    p "//  - %s" (cu.cpp_rule_names ~prefix:"" rl.rl_name)
  ) cu.cpp_rules;
  nl ()


let h_inspect_cpp_out (cpp_out : Cpp.cpp_output_t) () : unit = 
  p "// CPP Output Info:";
  p "//  - Module name: %s" cpp_out.co_modname;
  match cpp_out.co_ext_funcs with
   | [] -> p "//  - Ext functions: none"
   | l ->
       p "//  - Ext functions: %d" (List.length l);
       List.iter (fun ffi ->
         let name = (try ffi.ffi_name with _ -> "<anon>") in
          let arg_s = (try typ_to_string ffi.ffi_argtype with _ -> "<arg>") in
         let ret_s = (try typ_to_string ffi.ffi_rettype with _ -> "<ret>") in
         p "//    - %s : %s -> %s" name arg_s ret_s
       ) l

let contains s1 s2 =
  try
    let len = String.length s2 in
    for i = 0 to String.length s1 - len do
      if String.sub s1 i len = s2 then raise Exit
    done;
    false
  with Exit -> true
  

let internal_by_ffi_name (graph : Cuttlebone.Graphs.circuit_graph) =
  let tbl = Hashtbl.create 16 in
  List.iter
    (fun node ->
      match node.Hashcons.node with
      | Cuttlebone.Graphs.CExternal { f; internal; _ } ->
          Hashtbl.replace tbl f.ffi_name internal
      | _ -> ())
    graph.graph_nodes;
  tbl

let io_layouts (cout : Cpp.cpp_output_t)  (graph: Cuttlebone.Graphs.circuit_graph)  : io_layout list =
  let internal_tbl = internal_by_ffi_name graph in
  let (_final_off, acc_rev) =
    List.fold_left
      (fun (off, acc) ffi ->
         let name = ffi.ffi_name in
          let is_internal =
           match Hashtbl.find_opt internal_tbl name with
           | Some b -> b
           | None -> false
         in
         let io =
           if is_internal then Function
           else if contains name "output" || contains name "out" then Output
           else Input
         in
         let typ = if io = Input then ffi.ffi_rettype else ffi.ffi_argtype in
         let type_n = Cpp.cpp_type_of_type cout.co_program_info typ in
         let rettyp = ffi.ffi_rettype in
         let argtyp = ffi.ffi_argtype in
         let rettyp_n = Cpp.cpp_type_of_type cout.co_program_info rettyp in
         let argtyp_n = Cpp.cpp_type_of_type cout.co_program_info argtyp in
         let bits = typ_sz typ in
         let bytes = (bits + 7) / 8 in
         let entry = { name; io; typ; type_n; rettyp; argtyp; rettyp_n; argtyp_n; bits; bytes; off} in
         let next_off =
           match io with
           | Input -> off + bytes
           | _ -> off
         in
         (next_off, entry :: acc))
      (0, [])
      cout.co_ext_funcs
  in
  List.rev acc_rev



let register_layouts (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) : reg_layout list =
  let (_final_off, acc_rev) =
    Array.fold_left (fun (off, acc) r ->
      let kind = cu.cpp_register_kinds r in
      (* keep your current policy: only Value regs *)
      match kind with
      | Extr.Value ->
          let sg = cu.cpp_register_sigs r in
          let typ = reg_type sg in
          let bits = typ_sz typ in
          let bytes = (bits + 7) / 8 in
          let entry = { name = sg.reg_name; typ; kind; bits; bytes; off } in
          (off + bytes, entry :: acc)
      | _ ->
          (off, acc)
    ) (0, []) cu.cpp_registers
  in
  List.rev acc_rev

  let all_register_layouts (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) : reg_layout list =
  let (_final_off, acc_rev) =
    Array.fold_left (fun (off, acc) r ->
      let sg = cu.cpp_register_sigs r in
      let kind = cu.cpp_register_kinds r in
      let typ = reg_type sg in
      let bits = typ_sz typ in
      let bytes = (bits + 7) / 8 in
      let entry = { name = sg.reg_name; typ; kind; bits; bytes; off } in
      (off + bytes, entry :: acc)
    ) (0, []) cu.cpp_registers
  in
  List.rev acc_rev
let register_kind_to_string kind = 
  match kind with
  | Extr.Value -> "value"
  | Extr.Wire -> "wire"
  | Extr.Register -> "register"
  | Extr.EHR -> "ehr"


let macro_variables (name : string) (registers : 'a list)
    ~(get_name : 'a -> string) ~(get_bits : 'a -> int) () =
  p "#define %s(X) \\" name;
  let rec aux = function
    | [] -> ()
    | [r] -> p "   X(%s, %d)" (get_name r) (get_bits r)
    | r :: rs ->
        p "   X(%s, %d) \\" (get_name r) (get_bits r);
        aux rs
  in
  aux registers


let macro_var_io (name : string) (registers : 'a list)
    ~(get_name : 'a -> string) ~(get_bits : 'a -> int) () =
  p "#define %s(X) \\" name;
  let rec aux = function
    | [] -> ()
    | [r] -> p "   X(%s, %s, %s)" (get_name r) r.argtyp_n r.rettyp_n; (* needs fixing won't generalize*)
    | r :: rs ->
        p "   X(%s, %s,  %s) \\" (get_name r) r.argtyp_n r.rettyp_n;  (* needs fixing won't generalize*)
        aux rs
  in
  aux registers

let include_macros (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) (cout : Cpp.cpp_output_t) graph () = 
  let all_registers = all_register_layouts cu in
  let val_reisters = register_layouts cu in 
  let io_regs = io_layouts cout graph in
  let input_io = List.filter (fun r -> r.io = Input) io_regs in
  let output_io = List.filter (fun r -> r.io = Output) io_regs in
  macro_variables "ALL_REGISTERS" all_registers ~get_name:(fun r->r.name) ~get_bits:(fun r->r.bits) ();
  nl ();
  macro_variables "VAL_REGISTER" val_reisters ~get_name:(fun r->r.name) ~get_bits:(fun r->r.bits) ();
  nl ();
  macro_var_io "EXT_INPUTS" input_io ~get_name:(fun r->r.name) ~get_bits:(fun r->r.bits) (); 
  nl ();
  macro_var_io "EXT_OUTPUTS" output_io ~get_name:(fun r->r.name) ~get_bits:(fun r->r.bits) (); 
  nl ()

let h_registers (cu : (_,_,_,_,_,_) cpp_input_t) () : unit =
  p "// Registers:";
  List.iter (fun (r : reg_layout) ->
     let string_of_typ = typ_to_string r.typ in
     p "//  - %s : %s (kind: %s)" r.name string_of_typ (register_kind_to_string r.kind)
  ) (register_layouts cu);
  nl (); 
  p "// The input format of the input seed should be consistent with the input format expected by the module"


let h_static_seed_file () : unit = 
  p "   bool replay = false;"; 
  p "   const char *input_path = nullptr;";
  nl (); 
  p " if (argc == 3 && strcmp(argv[1], \"--replay\") == 0) {"; 
  p "     replay = true; "; 
  p "      input_path = argv[2];"; 
  p " } else if (argc == 2) {"; 
  p "     input_path = argv[1]; ";  
  p " } else {"; 
  p "     fprintf(stderr, \"Usage: %%s [--replay] <input_file>\\n\", argv[0]);"; 
  p "     return 1;"; 
  p " }"; 
  nl (); 
  p " FILE *f = fopen(input_path, \"rb\");";  
  p " if (!f) {"; 
  p "     fprintf(stderr, \"Error: unable to open %%s\\n\", input_path);"; 
  p "     return 1;"; 
  p " }";
  nl (); 
  p "   std::vector<uint8_t> %s; " n_seed_buf; 
  p "   fseek(f, 0, SEEK_END); // move to end of file" ; 
  p "   long file_size = ftell(f); // get file size"; 
  p "   fseek(f, 0, SEEK_SET); // move back to start of file"; 
  p "   if (file_size > 0){" ; 
  p "       %s.resize(file_size); // resize buffer to fit file size" n_seed_buf; 
  p "       fread(%s.data(), 1, file_size, f); // read file into buffer" n_seed_buf; 
  p "   } else {"; 
  p "       fprintf(stderr, \"Error: unable to read from %%s\\n\", input_path);";
  p "       return 1;";
  p "   }";
  p "   fclose(f); // close file"

let h_static_queue_dump () : unit =
  p "template <typename T>";
  p_fn ~typ:"inline void" ~name:"dump_hex_value" ~args:"FILE* out, const char* item_name, std::size_t idx, const T& v, int bit_width" (fun () ->
    p "const int hex_digits = (bit_width + 3) / 4;";
    p "if constexpr (std::is_integral_v<T>) {";
    p "  std::fprintf(out, \"%%s[%%zu]: 0x%%0*llx\\n\",";
    p "               item_name,";
    p "               idx,";
    p "               hex_digits,";
    p "               static_cast<unsigned long long>(v));";
    p "} else {";
    p "  const auto packed = prims::pack(v);";
    p "  std::fprintf(out, \"%%s[%%zu]: 0x%%0*llx\\n\",";
    p "               item_name,";
    p "               idx,";
    p "               hex_digits,";
    p "               static_cast<unsigned long long>(packed.v));";
    p "}" );
  nl ();
  p "template <typename QueueT>";
  p_fn ~typ:"inline void" ~name:"dump_queue_hex" ~args:"FILE* out, const char* title, const char* item_name, QueueT q, int bit_width" (fun () ->
    p "std::fprintf(out, \"--- %%s ---\\n\", title);";
    nl ();
    p "std::size_t idx = 0;";
    p "while (!q.empty()) {";
    p "  const auto v = q.front();";
    p "  q.pop();";
    p "  dump_hex_value(out, item_name, idx, v, bit_width);";
    p "  ++idx;";
    p "}";
    nl ();
    p "if (idx == 0) {";
    p "  std::fprintf(out, \"(empty)\\n\");";
    p "}";
  )


let input_size_calculation (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) (cout : Cpp.cpp_output_t)  graph () : unit = 
  let io_layouts_ = List.filter (fun r -> r.io = Input) (io_layouts cout graph) in
  let reg_layouts_ = (register_layouts cu) in
  let total_input_size_io = List.fold_left (fun acc (r : io_layout) -> acc + r.bytes) 0 io_layouts_ in (* could I just use last offset of register_sizes + last byte value ?*)
  let total_input_size_reg = List.fold_left (fun acc (r : reg_layout) -> acc + r.bytes) 0 reg_layouts_ in
  p "// Total input size IO: %d bytes" total_input_size_io; 
  p "   static constexpr std::size_t  %s =%d; " n_InputBytes total_input_size_io; 
  p "// Total input size REG: %d bytes" total_input_size_reg; 
  p "   static constexpr std::size_t  %s =%d; " n_InitBytes total_input_size_reg

let assign_val (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) () = 
  let register_sizes_ = register_layouts cu in
  List.iter (fun (r : reg_layout) -> 
    match r.typ with 
    | Bits_t _ -> if r.bits < r.bytes * 8 then 
                      p " %s.%s = prims::truncate<%d>(%s);" n_sim_init r.name r.bits r.name
  else
     p " %s.%s = prims::bits<%d>::mk(%s);" n_sim_init r.name r.bits r.name
    |  _ -> if r.bits < r.bytes * 8 then 
                      p " %s.%s = prims::unpack<decltype(%s.%s)>(prims::truncate<%d>(%s)); " n_sim_init r.name n_sim_init r.name r.bits r.name
  else
      p " %s.%s = prims::unpack<decltype(%s.%s)>(%s); " n_sim_init r.name n_sim_init r.name r.name (* is this sufficient ?*)
  ) register_sizes_

let pack_bits_from_bytes (cout : Cpp.cpp_output_t) () : unit =
  (* emit generic packer *)
  p "template <int BitWidth>";
  p "%s"
    "static prims::bits<BitWidth> pack_bits_from_bytes(const std::vector<uint8_t>& buf, \
     std::size_t offset, std::size_t nbytes) {";
  p "  prims::bits<BitWidth> acc = prims::bits<BitWidth>::mk(0);";
  p "  for (std::size_t i = 0; i < nbytes; ++i) {";
  p "    const uint8_t byte = (offset + i < buf.size()) ? buf[offset + i] : 0;";
  p "    const auto b = prims::widen<BitWidth>(prims::bits<8>::mk(byte));";
  p "    acc = acc | (b << (8 * i));";
  p "  }";
  p "  return acc;";
  p "}"; nl ()


let replay_block_initial () = 
    p " if (replay) { ";
    p "    %s::%s = %s::%s(input_path);" harness_ns n_crashlogP harness_ns n_decode_fn;
    p "    const std::string ruletrace_path = %s::%s + \"_ruletrace\";" harness_ns n_crashlogP; 
    p "    setenv(\"SIM_RULETRACE_FPATH\", ruletrace_path.c_str(), 1);"; 
    p "    fprintf(stderr, \"Replaying input from %%s\\n\", input_path);"; 
    p "    %s::%s(\"Initial State\", %s);" harness_ns fn_dump_state n_sim_init;
    p "}"

let replay_block_final () = 
    p " if (replay) { ";
    p "    %s::%s(\"Final State\", %s.snapshot().state);" harness_ns fn_dump_state n_sim; 
    p "}"


let h_simulator_setup (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) () = 
  let replay_init = with_output_to_buffer replay_block_initial in
  let replay_final = with_output_to_buffer replay_block_final in
  p_buffer replay_init;
  p "    %s::simulator %s(st); " harness_ns n_sim;
  p "    %s.set_assert_pred(%s);" n_sim n_assert_fn;
  p "    %s.set_assert_pred_final(%s);" n_sim n_assert_final;
  p "   %s.%s(plan.cycles, !replay); // run_fuzz is fuzzing method" n_sim Cpp.run_fuzz; 
  p_buffer replay_final


let decode_fn () = 
  p_fn ~typ:"static std::string " ~name:n_decode_fn ~args:"const char* input_path" (fun () ->
    p "    std::string in_path(input_path ? input_path : \"\");";
    p "    return in_path + \"_decoded\";";
  )
let dump_bits () =
  p "template <typename BitsT>";
  p_fn ~typ:"static void" ~name:"dump_bits_field" ~args:"FILE* out, const char* name, int width, BitsT value" (fun () ->
      p "  const auto packed = prims::pack(value);";
      p "  std::fprintf(out, \"%%s[%%d] = 0x%%08x\\n\", name, width, (unsigned)packed.v);";
    )
 
let set_inputs (cout : Cpp.cpp_output_t) graph () : unit =
  let io_layout = List.filter (fun r -> r.io = Input) (io_layouts cout graph) in
  p_fn ~typ:"static void" ~name:n_set_inputs_fn
    ~args:("const std::vector<uint8_t>& buf, const std::size_t " ^ nSeedPairs  ^ ",const std::size_t input_offset")
    (fun () ->
      p "  extfuns_impl::clear();";

      List.iter (fun r ->
        p "constexpr std::size_t %s_bytes = %d;" r.name r.bytes; (* probably redundant*)
      ) io_layout;

      let total_input_size =
        List.fold_left (fun acc (r : io_layout) -> acc + r.bytes) 0 io_layout
      in
      p "constexpr std::size_t total_bytes = %d;" total_input_size;
      p "for (std::size_t i = 0; i < %s; ++i) {" nSeedPairs;
      p "  const std::size_t base_off = input_offset + i * total_bytes;";

      List.iter (fun r ->
        p "  {";
        p "    const std::size_t off = base_off + %d;" r.off;
        match r.typ with 
        | Bits_t _ ->
        p "    prims::bits<%d> safe_%s = pack_bits_from_bytes<%d>(buf, off, %s_bytes);"
          (r.bytes * 8) r.name (r.bytes * 8) r.name;
        if r.bits < r.bytes * 8 then
          p "    extfuns_impl::%s_chan.push(prims::truncate<%d>(safe_%s));"
            r.name r.bits r.name
        else
          p "    extfuns_impl::%s_chan.push(prims::unpack<%s>(safe_%s));"
            r.name r.type_n r.name;
           p "  }";
        | _ -> 
          p "    prims::bits<%d> safe_%s = pack_bits_from_bytes<%d>(buf, off, %s_bytes);"
          (r.bytes * 8) r.name (r.bytes * 8) r.name;
        if r.bits < r.bytes * 8 then
          p "    extfuns_impl::%s_chan.push(prims::unpack<%s>(prims::truncate<%d>(safe_%s)));"
            r.name r.type_n r.bits r.name
        else
          p "    extfuns_impl::%s_chan.push(prims::unpack<%s>(safe_%s));"
            r.name r.type_n r.name;
        p "  }";
      ) io_layout;

      p "}";
    )

let set_init_fn (cu: (_,_,_,_,_,_) Cpp.cpp_input_t) () = 
   let register_sizes_ = register_layouts cu in
   let assign_val_buf = with_output_to_buffer (assign_val cu) in
   p_fn ~typ:"static void " ~name:n_set_init_fn ~args:("state_t &"^n_sim_init^", const std::vector<uint8_t>& "^n_seed_buf) (fun () ->
       List.iter (fun (r : reg_layout) -> 
       p "   prims::bits<%d> %s = prims::bits<%d>::mk(0);" (r.bytes * 8) r.name (r.bytes * 8); (* need to round up, is this enough ???, think we can ignore any input formatting and pass in binary directly ?  *)
       ) register_sizes_; 
       List.iter ( fun (r : reg_layout) -> 
       p " %s = pack_bits_from_bytes<%d>(%s, %d, %d);" r.name (r.bytes * 8) n_seed_buf r.off r.bytes; (* safe bit conversion *)
       ) register_sizes_ ;
       nl (); 
  p_buffer assign_val_buf )
  
let set_init_and_input_fn () : unit = 
  p_fn ~typ:"static void " ~name:n_set_init_and_input_fn ~args:("state_t &"^n_sim_init^", const std::vector<uint8_t>& "^n_seed_buf^", const std::size_t " ^ nSeedPairs) (fun () ->
  p "%s(%s, %s);" n_set_init_fn n_sim_init n_seed_buf; 
  p " %s(%s, %s, %s);" n_set_inputs_fn n_seed_buf nSeedPairs n_InitBytes
  )

let state_dump_fn (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) (cout : Cpp.cpp_output_t) graph () = 
  p_fn ~typ:"static void " ~name:fn_dump_state ~args:"const char* label, const state_t& st" (fun () ->
    p "  FILE* out = std::fopen(CrashLogPath.c_str(), \"a\");";
    p "  if (!out) {";
    p "    std::fprintf(stderr, \"Failed to open %%s: %%s\\n\",";
    p "                 CrashLogPath.c_str(), std::strerror(errno));";
    p "    out = stderr;";
    p "  }";
    nl ();
    p "  std::fprintf(out, \"=== %%s ===\\n\", label);";
    p "#define DUMP_FIELD(name, width) dump_bits_field(out, #name, width, st.name);";
    p "  ALL_REGISTERS(DUMP_FIELD)";
    p "#undef DUMP_FIELD";
    nl (); 
    let io_layout = List.filter (fun r -> r.io != Function) (io_layouts cout graph) in
    List.iter ( fun r -> 
      p " dump_queue_hex(out, \"extfuns %s queue\", \" %s \",  %s::%s_chan.q, %d);" r.name r.name n_extfuns_impl r.name r.bits
      )  (io_layout);
    nl (); 
    p "  if (out != stderr) {";
    p "    std::fclose(out);";
    p "  }";
  )

let str_extfuns (name : string) (cout : Cpp.cpp_output_t) graph () : unit  =
 p " struct %s {" name;
 nl ();
  p "    EXT_INPUTS(HARNESS_DECL_INPUT_CHANNEL)";
  p "    EXT_OUTPUTS(HARNESS_DECL_OUTPUT_CHANNEL)";
  p_fn ~typ:"static void" ~name:"clear" ~args:"" (fun () ->
    p "    EXT_INPUTS(HARNESS_CLEAR_INPUT_CHANNEL)";
    p "    EXT_OUTPUTS(HARNESS_CLEAR_OUTPUT_CHANNEL)"
  )
  ; List.iter (fun (r : io_layout) -> 
    match r.io with
    | Input -> p" auto %s(%s ready);" r.name (r.argtyp_n) 
    | Output -> p "%s %s(%s v);" (r.rettyp_n) r.name (r.argtyp_n)
    | Function -> () 
      ) (io_layouts cout graph)
  ; p "};"

let channel_macros (io: io) () = 
  let (arguments, p_or_s) = ("name, width, storage", "stored_t") in 
  let s_io = match io with 
    | Input -> "input"
    | Output -> "output" 
    | Function -> failwith "should not generate channel macros for functions" in
  p "#define DEF_%s_CHANNEL(%s) \\" (String.uppercase_ascii s_io) arguments; 
  p " %s_channel_fifo<%s::name##_%s> %s::name##_chan;" s_io n_extfuns_impl p_or_s n_extfuns_impl; 
  p "EXT_%sS(DEF_%s_CHANNEL)" (String.uppercase_ascii s_io) (String.uppercase_ascii s_io);
  p "#undef DEF_%s_CHANNEL" (String.uppercase_ascii s_io)

let channel_func(cout : Cpp.cpp_output_t) graph() : unit= 
let io_layout  = io_layouts cout graph in
  List.iter (fun r ->
    match r.io with   
    | Input -> 
                p_fn ~typ:"inline auto" ~name:(n_extfuns_impl^"::"^r.name) ~args:(Printf.sprintf "%s ready" (r.argtyp_n)) (fun () ->
                  p " // ready can be ignored"; 
                  p "  const %s_stored_t p = %s_chan.pop_or_zero();" r.name r.name;
                  p "  return p;" )
    | Output -> p_fn ~typ:(Printf.sprintf "inline %s" (r.rettyp_n)) ~name:(n_extfuns_impl^"::"^r.name) ~args:(Printf.sprintf "%s v" (r.argtyp_n)) (fun () ->
                  p "  %s_chan.push(static_cast<%s_stored_t>(v));" r.name r.name;
                  p "  return bits<1>::mk(true);")
    | Function -> ()
  ) io_layout 

let ns_harness (name : string) (cu : (_,_,_,_,_,_) Cpp.cpp_input_t) (cout : Cpp.cpp_output_t) (pg) () =
  let dump_state = with_output_to_buffer (state_dump_fn cu cout pg) in 
  let set_init_fn_buf = with_output_to_buffer (set_init_fn cu) in
  let h_sim_buf = with_output_to_buffer (h_sim_setup cout.co_modname) in
  let p_decode_fn = with_output_to_buffer decode_fn in
  let dump_bits_fn = with_output_to_buffer dump_bits in
  let str_extfuns_fn = with_output_to_buffer (str_extfuns n_extfuns_impl cout pg) in
  let channel_macro_in = with_output_to_buffer (channel_macros Input) in
  let channel_macro_out = with_output_to_buffer (channel_macros Output) in
  let channel_func_buf = with_output_to_buffer (channel_func cout pg) in
  let set_inputs_buf = with_output_to_buffer (set_inputs cout pg) in
  let pack_bb_buf = with_output_to_buffer (pack_bits_from_bytes cout) in
  let dump_queue = with_output_to_buffer h_static_queue_dump in
  let input_size_cal = with_output_to_buffer (input_size_calculation cu cout pg) in
  let init_and_input_fn = with_output_to_buffer (set_init_and_input_fn) in
   p "namespace %s {" name;
   p "    struct extfuns_impl; ";
   p "    using extfuns_t = extfuns_impl;"; 
   p "}"; 
  p "namespace %s {" name;
  nl (); 
  p_buffer input_size_cal; 
  nl (); 
  p_buffer str_extfuns_fn;
  nl (); 
  p_buffer h_sim_buf;
  nl ();
  p_buffer channel_macro_in;
  nl ();
  p_buffer channel_macro_out;
  nl (); 
  p_buffer channel_func_buf;
  nl ();
  p_buffer p_decode_fn;
  nl (); 
  p_buffer dump_bits_fn;
  nl (); 
  p_buffer pack_bb_buf; 
  nl ();
  p_buffer dump_queue; 
  nl (); 
  p_buffer dump_state;
  nl ();
  p_buffer set_inputs_buf;
  nl ();
  p_buffer set_init_fn_buf;
  nl (); 
  p_buffer init_and_input_fn; 
  nl (); 
  p "} // namespace %s" name



let mode_config () : unit = 
   p "%s::plan plan;" n_mode_helper;
   nl (); 
   p "if (!%s::prepare_input<%s::%s,%s::%s>(%s, plan)) {" n_mode_helper harness_ns n_InitBytes harness_ns n_InputBytes n_seed_buf; 
   p " return 0; "; 
   p "}"; 
   nl (); 
   p " %s::simulator::state_t %s = %s::simulator::initial_state();" harness_ns  n_sim_init harness_ns; 
   nl (); 
   p " BEAK_APPLY_FUZZ_MODE(%s, %s, %s, plan);" harness_ns n_sim_init n_seed_buf


let h_main (_modname : string) (cpp_in : (_,_,_,_,_,_) Cpp.cpp_input_t) (cout : Cpp.cpp_output_t) pg () : unit = 
  let p_static_seed = with_output_to_buffer h_static_seed_file in
  let h_sim = with_output_to_buffer (h_simulator_setup cpp_in) in
  let mode_config_ = with_output_to_buffer (mode_config) in
  p_fn ~typ:"int" ~name:"main" ~args:"int argc, char **argv" (fun () ->
    nl ();  
    p_buffer p_static_seed; 
    nl (); 
    p_buffer mode_config_; 
    nl (); 
    p_buffer h_sim;
    nl (); 
    p "  return 0;"
  )


  
let h_inspect_cpp_out (cpp_out : Cpp.cpp_output_t) () : unit = 
  p "// CPP Output Info:";
  p "//  - Module name: %s" cpp_out.co_modname;
  (match cpp_out.co_ext_funcs with
   | [] -> p "//  - Ext functions: none"
   | l ->
       p "//  - Ext functions: %d" (List.length l);
       List.iter (fun sign ->
         let name = (try sign.ffi_name with _ -> "<anon>") in
        let arg_s = (try typ_to_string sign.ffi_argtype with _ -> "<arg>") in
         let ret_s = (try typ_to_string sign.ffi_rettype with _ -> "<ret>") in 
         (* let sp_arg typ = sprintf "const %s arg" (typ_to_string (Cpp.cpp_type_of_type typ)) in *)
         let typp = Cpp.cpp_type_of_type cpp_out.co_program_info sign.ffi_rettype in
          p_comment "%s %s;" typp sign.ffi_name; 
         p "//    - %s : %s -> %s" name arg_s ret_s  
       ) l);
  List.iter (fun r ->
    let name = r.reg_name in
    let typ = r |> reg_type |> typ_to_string in
    p "//  - Register %s : %s" name typ
  ) cpp_out.co_register_sigs;
  nl ()
let h_cpp (cpp_out : Cpp.cpp_output_t) (cpp_in : (_,_,_,_,_,_) Cpp.cpp_input_t) (pkg_graph) () =
    let modname = cpp_out.co_modname in
    let preamble_buf = with_output_to_buffer (h_preamble modname cpp_in) in 
    let description_buf = with_output_to_buffer (h_description modname) in
    let registers_buf = with_output_to_buffer (h_registers cpp_in) in 
    let inspect_cpp_out = with_output_to_buffer (h_inspect_cpp_out cpp_out) in
    let macros = with_output_to_buffer (include_macros cpp_in cpp_out pkg_graph) in
    let ns_harness_buf = with_output_to_buffer (ns_harness harness_ns cpp_in cpp_out pkg_graph) in
    p_buffer inspect_cpp_out;
    p_buffer preamble_buf;
    p_buffer description_buf; 
    p_buffer macros; 
    p_buffer registers_buf;
    p_buffer ns_harness_buf;
    nl (); 
    h_main modname cpp_in cpp_out pkg_graph ()

let write_harness_cpp (target_dpath : string) (cpp_out :Cpp.cpp_output_t) (cpp_in : (_,_,_,_,_,_) Cpp.cpp_input_t) (pkg_graph) : unit =
  let fpath = Filename.concat target_dpath harness_cpp_fname in
  let out_buf = with_output_to_buffer (h_cpp cpp_out cpp_in pkg_graph) in
  with_output_to_file fpath Buffer.output_buffer out_buf 

  
let main target_dpath (cpp_out :Cpp.cpp_output_t) (cpp_in : (_,_,_,_,_,_) Cpp.cpp_input_t) (pkg_graph) =
  write_harness_cpp target_dpath cpp_out cpp_in pkg_graph
 